environments:
  local:
    PORT: "9095"
    MONGO_URI: "mongodb+srv://user:mJ7+hbvf@cluster0.dxdmk.mongodb.net/"
    DB: "petalPix"
    COLLECTION: "users"
  production:
    PORT: "9095"
    MONGO_URI: "mongodb://apiserviceuser:UAToHan%5E8Z%232oLku@uccdb.airtel.in:37017/compdb"
    DB: "compdb"
    COLLECTION: "testcollxn"

    # mongodb://apiserviceuser:UAToHan%5E8Z%232oLku@uccdb.airtel.in:37017/compdb
    