environments:
  local:
    PORT: "9095"
    MONGO_URI: "mongodb+srv://user:mJ7+hbvf@cluster0.dxdmk.mongodb.net/"
    DB: "petalPix"
    COLLECTION: "users"
  production:
    PORT: "9095"
    MONGO_URI: ""
    DB: "compdb"
    COLLECTION: "testcollxn"
